# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
