# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180303_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(default='bla'),
        ),
    ]
