# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
