# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180310_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description',
            new_name='description2',
        ),
    ]
