# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180311_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description2',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='title',
            new_name='link',
        ),
    ]
